name = "StoreMD"
client_id = "7a43433287b773fd9222fe7d04fd98e0"
application_url = "https://storemd.vercel.app"
embedded = false

[auth]
redirect_urls = ["https://storemd-api-production.up.railway.app/api/v1/auth/callback"]

[webhooks]
api_version = "2026-04"
