# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e857f2fb3f3944ed97d0c275c8ab65"
name = "StoreMD"
application_url = "https://storemd.vercel.app"
embedded = false

[access_scopes]
scopes = "read_products,read_themes,read_orders,read_script_tags"

[auth]
redirect_urls = [
  "https://storemd-api-production.up.railway.app/api/v1/auth/callback"
]

[webhooks]
api_version = "2026-04"

[build]
dev_store_url = "storemdtest.myshopify.com"
