# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e857f2fb3f3944ed97d0c275c8ab65"
name = "StoreMD"
application_url = "https://storemd.vercel.app"
embedded = true

[build]
dev_store_url = "storemdtest.myshopify.com"

[webhooks]
api_version = "2026-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://storemd-api-production.up.railway.app/api/v1/webhooks/customers/redact"
  customer_data_request_url = "https://storemd-api-production.up.railway.app/api/v1/webhooks/customers/data_request"
  shop_deletion_url = "https://storemd-api-production.up.railway.app/api/v1/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_script_tags,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://storemd-api-production.up.railway.app/api/v1/auth/callback"
]
